-- ============================================================
-- InDrive Finanzas — Esquema para Supabase (PostgreSQL)
-- Copiar y pegar en: SQL Editor -> New query -> Run
--
-- IMPORTANTE: el orden de las columnas es EXACTAMENTE el del
-- archivo indrive_finanzas.db. El codigo de main.py lee columnas
-- por posicion (r[7], r[12], r[15], p[1..3]) en los SELECT *,
-- asi que cualquier cambio de orden rompe la app.
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABLAS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.transacciones (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha       TEXT NOT NULL,
    cuenta      TEXT NOT NULL,
    tipo        TEXT NOT NULL,
    monto       REAL NOT NULL,
    comision    REAL DEFAULT 0,
    viajes      INTEGER DEFAULT 0,
    km          REAL DEFAULT 0,
    categoria   TEXT NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS public.clientes (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      TEXT NOT NULL,
    deuda_total REAL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.casa_pagos (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_pago          TEXT,
    monto               REAL DEFAULT 0,
    mes_corresponde     TEXT,
    pendiente           REAL DEFAULT 0,
    pago_hasta          TEXT,
    saldo_pendiente     REAL DEFAULT 0,
    tasa_aseo           REAL DEFAULT 0,
    deposito            REAL DEFAULT 0,
    luz                 REAL DEFAULT 0,
    gasto_fecha         TEXT,
    gasto_concepto      TEXT,
    gasto_monto         REAL DEFAULT 0,
    pago_adic_fecha     TEXT,
    pago_adic_monto     REAL DEFAULT 0,
    ahorro              REAL DEFAULT 0,
    mes_pendiente       TEXT,
    pendiente_extra     REAL DEFAULT 0,
    pendiente_por_pagar REAL DEFAULT 0,
    cliente_id          INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.casa_pagos_usuario (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha           TEXT,
    monto           REAL DEFAULT 0,
    mes_corresponde TEXT,
    pendiente       REAL DEFAULT 0,
    pago_hasta      TEXT,
    cliente_id      INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.casa_aseo_pagos (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha        TEXT,
    monto_pagado REAL DEFAULT 0,
    cliente_id   INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.casa_ahorro (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha      TEXT,
    monto      REAL DEFAULT 0,
    concepto   TEXT,
    ahorro     REAL DEFAULT 0,
    cliente_id INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.casa_deuda_pagos (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha        TEXT,
    monto_pagado REAL DEFAULT 0,
    descripcion  TEXT,
    cliente_id   INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.casa_gastos (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha      TEXT,
    concepto   TEXT,
    monto      REAL DEFAULT 0,
    tipo       TEXT DEFAULT 'casa',
    cliente_id INTEGER DEFAULT 1
);

-- ------------------------------------------------------------
-- 2. SEGURIDAD — Row Level Security
--    Sin sesion iniciada la API devuelve 0 filas.
-- ------------------------------------------------------------

ALTER TABLE public.transacciones      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.casa_pagos         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.casa_pagos_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.casa_aseo_pagos    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.casa_ahorro        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.casa_deuda_pagos   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.casa_gastos        ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'transacciones', 'clientes', 'casa_pagos', 'casa_pagos_usuario',
        'casa_aseo_pagos', 'casa_ahorro', 'casa_deuda_pagos', 'casa_gastos'
    ] LOOP
        EXECUTE FORMAT('DROP POLICY IF EXISTS "acceso_autenticado" ON public.%I', t);
        EXECUTE FORMAT(
            'CREATE POLICY "acceso_autenticado" ON public.%I
             FOR ALL TO authenticated
             USING (true) WITH CHECK (true)',
            t
        );
    END LOOP;
END $$;

-- ------------------------------------------------------------
-- 3. VERIFICACION
-- Debe devolver 8 filas con rlsgenrel = true
-- ------------------------------------------------------------
-- SELECT c.relname, c.relrowsecurity
-- FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
-- WHERE n.nspname = 'public' AND c.relkind = 'r'
-- ORDER BY c.relname;

-- ------------------------------------------------------------
-- 4. ALMACENAMIENTO
-- Bucket publico para las actualizaciones de la app:
--   apk/latest.json   -> {"version","version_code","apk","nota","sha256","peso"}
--   apk/<archivo>.apk -> el APK firmado
-- El bucket es publico para que cualquier telefono pueda leerlo sin sesion
-- (el actualizador usa /storage/v1/object/public/...). La escritura solo
-- la hace quien tenga una sesion autenticada o la clave de servicio.
-- ------------------------------------------------------------

INSERT INTO storage.buckets (id, name, public)
VALUES ('apk', 'apk', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "apk_lectura_publica" ON storage.objects;
CREATE POLICY "apk_lectura_publica" ON storage.objects
    FOR SELECT TO public
    USING (bucket_id = 'apk');

DROP POLICY IF EXISTS "apk_escritura" ON storage.objects;
CREATE POLICY "apk_escritura" ON storage.objects
    FOR ALL TO authenticated
    USING (bucket_id = 'apk') WITH CHECK (bucket_id = 'apk');
